server:
  port: 8080

env:
  folder: C:\Users\user\Desktop\DUMMY_DATA\
  # folder: \\172.16.150.135\2_팀 공유 폴더\2) 학습 DATAset_Superb AI\Export 다운로드 버전\
  write: C:\Users\user\Desktop\test\
spring:
  profiles:
    active: dev